# name of github action
name: CI

# when to run the action
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# jobs to run
jobs:
  build:
    #use node 18
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test
      - name: Start
        run: npm start